scss:
	pushd scss && sass --cache-location /tmp/.sass-cache --scss main.scss ../static/compiled.css && popd

debug:
	pushd scss && sass --cache-location /tmp/.sass-cache --line-numbers --scss main.scss ../static/compiled.css && popd

.PHONY: scss debug
